# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('posts', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('user_name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=5000)),
                ('user_name', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('forum_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.ForumDB')),
            ],
        ),
    ]
