# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-25 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20160925_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threaddb',
            old_name='counting',
            new_name='count',
        ),
    ]
