# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-25 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20160925_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='threaddb',
            name='profile_pic',
            field=models.FileField(blank=True, max_length=500, upload_to=b''),
        ),
    ]
