# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_threaddb_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumdb',
            name='fid',
            field=models.IntegerField(default=0),
        ),
    ]
