# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0010_threaddb_foid'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumdb',
            name='house',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
