# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0012_mypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
