# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0014_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='threaddb',
            name='delflag',
            field=models.IntegerField(default=0),
        ),
    ]
