# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0015_threaddb_delflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threaddb',
            name='profile_pic',
            field=models.FileField(blank=True, max_length=500, upload_to=''),
        ),
    ]
