# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomq', '0002_remove_quiz_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='score',
        ),
        migrations.RemoveField(
            model_name='rquiz',
            name='score',
        ),
    ]
