# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomq', '0003_auto_20160915_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='rquiz',
            name='tanswer',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
