# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomq', '0005_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rquiz',
            name='imgee',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
