# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usr',
            name='keym',
        ),
        migrations.DeleteModel(
            name='usr',
        ),
    ]
