# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_myusr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myusr',
            old_name='myid',
            new_name='user',
        ),
    ]
