# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_myusr_preferredh'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusr',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myusr',
            name='ranktemp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myusr',
            name='score2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myusr',
            name='totals',
            field=models.IntegerField(default=0),
        ),
    ]
