# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20160921_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusr',
            name='level1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myusr',
            name='level2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myusr',
            name='level3',
            field=models.IntegerField(default=0),
        ),
    ]
