# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20160923_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusr',
            name='level1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='myusr',
            name='level2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='myusr',
            name='level3',
            field=models.IntegerField(default=1),
        ),
    ]
