# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20160923_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusr',
            name='score11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myusr',
            name='score12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myusr',
            name='score21',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myusr',
            name='score22',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myusr',
            name='score31',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myusr',
            name='score32',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myusr',
            name='score41',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myusr',
            name='score42',
            field=models.IntegerField(default=0),
        ),
    ]
