# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-25 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20160924_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusr',
            name='level4',
            field=models.IntegerField(default=1),
        ),
    ]
