# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-25 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusr',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
