# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_myusr_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusr',
            name='bonfl',
            field=models.IntegerField(default=0),
        ),
    ]
