# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('background_color', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.FileField(blank=True, max_length=200, null=True, upload_to=b'')),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('image1', models.FileField(blank=True, max_length=550, null=True, upload_to=b'')),
                ('caption1', models.CharField(blank=True, max_length=250, null=True)),
                ('main_text', models.CharField(blank=True, max_length=500, null=True)),
                ('article1', models.CharField(blank=True, max_length=2000, null=True)),
                ('article2', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
