# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdb',
            name='image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newsdb',
            name='image1',
            field=models.FileField(blank=True, max_length=550, null=True, upload_to=''),
        ),
    ]
